repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.0
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --config=pyproject.toml ]
      files: ^src/

    # Run the formatter.
    - id: ruff-format
      args: [ --config=pyproject.toml ]
      files: ^src/